###Docker Compose file for Message App###
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    # container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: messageappacrdevsusmitha.azurecr.io/backend-app-susmitha:latest
    # container_name: backend-app
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/message_db
      # - CORS_ALLOWED_ORIGINS=http://localhost:8080
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Calcutta

  frontend:
    image: messageappacrdevsusmitha.azurecr.io/frontend-app-susmitha:latest
    # container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080   # must match backend service name

volumes:
  mongo-data: